/**
 * DIBS Backend — Settlement Partner Integration Service
 *
 * Transmits settlement instructions to regulated partners.
 * DIBS does NOT execute regulated functions — it transmits instructions to
 * regulated banking, payment, escrow, custody, lending, and insurance counterparties.
 *
 * Idempotency: one settlement instruction per release authorization.
 * Bank account validation required before instruction transmission.
 *
 * Status Model: pending → sent → confirmed | exception | failed
 */

import { EventStore, EventType } from '../audit/event-store';

export type SettlementStatus = 'pending' | 'sent' | 'confirmed' | 'exception' | 'failed';

export interface SettlementInstruction {
  instructionId: string;
  requestId: string;
  amount: number;
  paymentDestination: string;
  settlementPartner: string;
  instructionHash: string;
  status: SettlementStatus;
  timestamp: string;
  tenantId: string;
  confirmationHash?: string;
  confirmedAmount?: number;
  confirmedTimestamp?: string;
  exceptionType?: string;
  exceptionDescription?: string;
}

export interface BankAccountValidation {
  accountVerified: boolean;
  accountName?: string;
  accountType?: string;
  routingNumber?: string;
  verificationTimestamp?: string;
  failureReason?: string;
}

/**
 * Validate the settlement/bank account before transmitting instructions.
 * Blocks instruction transmission if account is not verified.
 */
export function validateBankAccount(
  paymentDestination: string,
  validation: BankAccountValidation
): { valid: boolean; failureReason?: string } {
  if (!validation.accountVerified) {
    return {
      valid: false,
      failureReason: validation.failureReason || 'SETTLEMENT_ACCOUNT_NOT_VERIFIED',
    };
  }
  if (!validation.accountName || !validation.accountType) {
    return {
      valid: false,
      failureReason: 'INCOMPLETE_ACCOUNT_VALIDATION',
    };
  }
  return { valid: true };
}

/**
 * Generate a deterministic instruction hash for idempotency.
 * One instruction per release authorization — duplicate instructions for the same
 * requestId must produce the same hash and be rejected.
 */
export function generateInstructionHash(
  requestId: string,
  amount: number,
  paymentDestination: string,
  settlementPartner: string
): string {
  // TODO: Use proper SHA-256 hashing in production
  const payload = `${requestId}:${amount}:${paymentDestination}:${settlementPartner}`;
  let hash = 0;
  for (let i = 0; i < payload.length; i++) {
    const char = payload.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash = hash & hash;
  }
  return `0x${Math.abs(hash).toString(16).padStart(8, '0')}`;
}

export class SettlementService {
  private instructions: Map<string, SettlementInstruction> = new Map();
  private requestIndex: Map<string, string> = new Map(); // requestId → instructionId (idempotency)

  constructor(private eventStore: EventStore) {}

  /**
   * Create and transmit a settlement instruction.
   * Idempotent: if an instruction already exists for this requestId, returns the existing one.
   */
  async createInstruction(
    params: {
      requestId: string;
      amount: number;
      paymentDestination: string;
      settlementPartner: string;
      tenantId: string;
      bankValidation: BankAccountValidation;
    }
  ): Promise<SettlementInstruction> {
    // Idempotency check — one instruction per release authorization
    const existingId = this.requestIndex.get(params.requestId);
    if (existingId) {
      const existing = this.instructions.get(existingId);
      if (existing) return existing;
    }

    // Bank account validation
    const bankCheck = validateBankAccount(params.paymentDestination, params.bankValidation);
    if (!bankCheck.valid) {
      throw new Error(`SETTLEMENT_BLOCKED: ${bankCheck.failureReason}`);
    }

    const instructionId = `set_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
    const instructionHash = generateInstructionHash(
      params.requestId,
      params.amount,
      params.paymentDestination,
      params.settlementPartner
    );

    const instruction: SettlementInstruction = {
      instructionId,
      requestId: params.requestId,
      amount: params.amount,
      paymentDestination: params.paymentDestination,
      settlementPartner: params.settlementPartner,
      instructionHash,
      status: 'pending',
      timestamp: new Date().toISOString(),
      tenantId: params.tenantId,
    };

    this.instructions.set(instructionId, instruction);
    this.requestIndex.set(params.requestId, instructionId);

    // Transmit to settlement partner (abstracted — actual API call is a stub)
    await this.transmitToPartner(instruction);

    // Emit immutable event
    await this.eventStore.append({
      eventId: '', // Generated by event store
      timestamp: '',
      previousEventHash: '',
      eventType: 'SETTLEMENT_INSTRUCTION_SENT' as EventType,
      actorId: 'settlement_service',
      actorRole: 'system',
      tenantId: params.tenantId,
      payloadHash: instructionHash,
      policyVersion: '',
      metadata: {
        instructionId,
        requestId: params.requestId,
        amount: params.amount,
        paymentDestination: params.paymentDestination,
        settlementPartner: params.settlementPartner,
      },
    });

    return instruction;
  }

  /**
   * Transmit instruction to regulated settlement partner.
   * This is a stub — actual implementation will call partner-specific APIs
   * (FedWire, SWIFT, ACH, escrow provider, etc.)
   */
  private async transmitToPartner(instruction: SettlementInstruction): Promise<void> {
    // TODO: Implement actual partner API integration
    // - FedWire gateway
    // - SWIFT message
    // - ACH transfer
    // - Escrow provider API
    // - Payment processor API

    instruction.status = 'sent';
    // TODO: Handle transmission failure → status = 'failed'
  }

  /**
   * Record a settlement confirmation from a regulated partner.
   */
  async recordConfirmation(
    instructionId: string,
    confirmation: {
      confirmationHash: string;
      confirmedAmount: number;
      confirmedTimestamp: string;
      tenantId: string;
    }
  ): Promise<SettlementInstruction> {
    const instruction = this.instructions.get(instructionId);
    if (!instruction) {
      throw new Error(`SETTLEMENT_INSTRUCTION_NOT_FOUND: ${instructionId}`);
    }

    instruction.status = 'confirmed';
    instruction.confirmationHash = confirmation.confirmationHash;
    instruction.confirmedAmount = confirmation.confirmedAmount;
    instruction.confirmedTimestamp = confirmation.confirmedTimestamp;

    // Emit immutable event
    await this.eventStore.append({
      eventId: '',
      timestamp: '',
      previousEventHash: '',
      eventType: 'SETTLEMENT_CONFIRMED' as EventType,
      actorId: 'settlement_service',
      actorRole: 'system',
      tenantId: confirmation.tenantId,
      payloadHash: confirmation.confirmationHash,
      policyVersion: '',
      metadata: {
        instructionId,
        requestId: instruction.requestId,
        confirmedAmount: confirmation.confirmedAmount,
        settlementPartner: instruction.settlementPartner,
      },
    });

    return instruction;
  }

  /**
   * Record a settlement exception.
   */
  async recordException(
    instructionId: string,
    exception: {
      exceptionType: string;
      exceptionDescription: string;
      tenantId: string;
    }
  ): Promise<SettlementInstruction> {
    const instruction = this.instructions.get(instructionId);
    if (!instruction) {
      throw new Error(`SETTLEMENT_INSTRUCTION_NOT_FOUND: ${instructionId}`);
    }

    instruction.status = 'exception';
    instruction.exceptionType = exception.exceptionType;
    instruction.exceptionDescription = exception.exceptionDescription;

    // Emit immutable event
    await this.eventStore.append({
      eventId: '',
      timestamp: '',
      previousEventHash: '',
      eventType: 'SETTLEMENT_EXCEPTION' as EventType,
      actorId: 'settlement_service',
      actorRole: 'system',
      tenantId: exception.tenantId,
      payloadHash: instruction.instructionHash,
      policyVersion: '',
      metadata: {
        instructionId,
        requestId: instruction.requestId,
        exceptionType: exception.exceptionType,
        exceptionDescription: exception.exceptionDescription,
      },
    });

    return instruction;
  }

  getInstruction(instructionId: string): SettlementInstruction | undefined {
    return this.instructions.get(instructionId);
  }

  getInstructionByRequest(requestId: string): SettlementInstruction | undefined {
    const instructionId = this.requestIndex.get(requestId);
    return instructionId ? this.instructions.get(instructionId) : undefined;
  }
}
